package com.hrms.testng.lib_function;

import org.openqa.selenium.WebDriver;
public class Global_Data {

	// Driver Access
	
	WebDriver driver;
	
	
	// Testing Data's
	
	public String url 				= 	"http://127.0.0.1/orangehrm-2.6/login.php" ;
	public String username	 		= 	"admin";
	public String wrong_username 	= 	"adimi";
	public String password 			= 	"admin";
	public String wrong_password 	= 	"minda";
	public String oldpassword 		= 	"admin";
	public String wrong_oldpassword	=	"minus";
	public String newPassword 		= 	"admin";
	public String confirmPassword	= 	"admin";
	public String wrong_confirmPassword ="minus";
	public String frame				= 	"rightMenu";
	public String tctCompanyName	=		"DLF IPL";
	public String txID				=		"DLF26";
	public String txtNaics			= 		"DLF NACCIs";
	public String txtphone			= 		"9876543210";
	public String txtfax			=		"3348877";
	public String dropdown_list		=		"India";
	public String txtaddress		=		"Rashtiya ,Phulwari Sharif,Kerla";
	public String  txtCity			=		"Pondicahery";
	public String txtState			=			"Kerla";
	public String txtZip			=		"801505";
	public String txtCommnet		=		"Data needs to submit";
	public String txt_loc_name		= 		"Location Name";
	public String txtloc_city		=		"locaton_city";
	public String txt_visble		=		"ID";
	public String txt_sear			=		"LOC002";
	public String linktext			=		"Job";
	public String jobtext			=		"Job Titles";
	public String jobtitlename		=		"TataIPL";
	public String txtJobTitle_Desc	=		"IPL is very Famous";
	public String txtJTComments		=		"T20 over for match ";
	public String namegradepay		=		"Google";
	public String curr_select		=		"Australian Dollar";
	public String min_salry			=		"450000";
	public String max_salry			=		"12000000";
	public String stp_incre			=		"500000";
	public String speci_txtFidName	=		"Data Scientist";	
	public String speci_txtDesc		=		"Works very easiy";
	public String speci_duties		=		"Regular";
	public String txt_pay_loc_name	=		"SAL029";	
	public String txt_last			=		"Pandey";
	public String  txt_first		=		"Ritesh DeshMujkh";
	public String search_PIM		=		"0058";
	public String DOB				=		"2000/08/32";
	public String txtemail_			=		"abc@gmail.com";
	public String emerge_contact	=		"Disha Patni";
	public String emerg_contac_rel	=		"Wife";
	public String emerg_phone		=		"9876543219";
 	public String dependt_name		=		"Pradhan Jee";
 	public String depent_rel		=		"Father";
 	public String passport_no		=		"98765678";
 	public String idstatuse			=		"Valid";
 	public String idstus_revi		=		"2024-03-21";
 	public String countr_drop		=		"cmbPPCountry";
 	public String issue_date		=		"2024-08-31";
 	public String expiry_date		=		"2030-08-31";
 	public String impg_comment		=		"This passport is valid for all country excpect pak";
 	public String joe_date			=		"2026-07-05";
 	public String basic_pay_Aus		=		"5000000";
 	public String txt_workexp		=		"LabCorp";
 	public String txt_work_start	=		"2021-09-03";
 	public String txt_wortitle		=		"Data Transfer Associate";
 	public String txt_enddate		=		"2023-10-31";
 	// Testing Objects
	
	public String txt_LoginName 		= 	"txtUserName";
	public String txt_password  		= 	"txtPassword";
	public String btn_Login				= 	"Submit";
	public String link_Logout			= 	"Logout";
	public String btn_Clear 			= 	"clear";
	public String txt_title 			= 	"OrangeHRM";
	public String txt_beofre_title 		= 	"OrangeHRM - New Level of HR Management";
	public String text_data		 		= 	"bodyTXT";
	public String link_text 			= 	"Change Password";
	public String btn_save				= 	"editBtn";
	public String txtOldPassword 		= 	"txtOldPassword";
	public String wrong_txtOldPassword	=	"txtOldPassword";
	public String txtNewPassword		=	"txtNewPassword";
 	public String txtConfirmPassword	= 	"txtConfirmPassword";
 	public String wrong_txtConfirmPassword	= 	"txtConfirmPassword";
 	public String btn_Reset				=		"//input[@value = 'Reset']";
 	public String btn_menu				=  	"Admin";
	public String btn_menu_txt			=	"Company Info";
	public String btn_submenu_txt		=    "General";
	public String txt_compnayName		=	"txtCompanyName";
	public String txtId					=		"txtTaxID";
	public String txt_Nacis				= 		"txtNAICS";
	public String txt_Phone				=		"txtPhone";
	public String txt_fax				=		"txtFax";
	public String dropdown				= 		"cmbCountry";
	public String txt_address			=   	"txtStreet1";
	public String txt_City				= 		"cmbCity";
	public String txt_state				=		"txtState";
	public String txt_Zip				=		"txtZIP";
	public String txt_mobile			=		"txtMobile";
	public String contacttxt_ZIp		=		"txtzipCode";
	public String txt_Comment			= 		"txtComments";
	public String txt_location			=		"Locations";
	public String save_btn				=		"//input[@value = 'Add']";
	public String location_txtt			= 		"txtLocDescription";
	public String location_city			=		"cmbDistrict";
	public String txt_address_loc		= 		"txtAddress";
	public String txt_droplist			=		"loc_code";
	public String txt_searchdata		=		"loc_name";	
	public String searchbtn				=		"//input[@value = 'Search']";
	public String checkbox				=		"chkLocID[]";
	public String delete_btn			=		"//input[@value = 'Delete']";
	public String back_funct			=		"//input[@value = 'Back']";
	public String job_title_name		=		"txtJobTitleName";
	public String txtJobTitleDesc		=		"txtJobTitleDesc";
	public String txtJobTitleComments	=		"txtJobTitleComments";
	public String jbdrop_down 			=		"cmbJobSpecId";
	public String jobspecif_drop		=		"cmbPayGrade";
	public String paygrade				=		"//input[@value= 'Add Pay Grade']";
	public String namegrade				=		"txtSalGrdDesc";
	public String save_btnpay			=		"//input[@value = 'Save']";
	public String txt_currency			=		"cmbUnAssCurrency";
	public String min_Salary			=		"txtMinSal";
	public String max_salary			=		"txtMaxSal";
	public String stp_incer				=		"txtStepSal";
	public String saveBtn				=		"saveBtn";
	public String value_search			=		"JOB001";
	public String txtjobspecif			=		"Job Specifications";
	public String txtFieldName			=		"txtFieldName";
	public String desc_txtDesc			=		"txtDesc";
	public String duties_txtDuties		=		"txtDuties";
	public String id_select				=		"1";
	public String txtpaygrade			=		"Pay Grades";	
	public String PIM_item				=		"PIM";
	public String employee_menu			=		"Employee List";
	public String txtlast				=		"txtEmpLastName";
	public String txtFirst				=		"txtEmpFirstName";
	public String photo_id				=		"photofile";
	public String personal_edit			=		"EditMain";
	public String personal_DOB			=		"DOB";
	public String personal_checbox		=		"chkSmokeFlag";
	public String personal_gender		=		"gender2";
	public String personal_marriage		=		"cmbMarital";
	public String personal_Reset		=		"btnClearPers";
	public String linktext_Contact		=		"Contact Details";
	public String txt_Email				=		"txtOtherEmail";
	public String txt_Edit				=		"btnEditContact";
	public String txt_Contact			=		"btnClearContact";
	public String txr_Emergency			=		"Emergency Contact(s)";
	public String txt_emerge_name		=		"txtEConName";
	public String txt_emerg_relat		=		"txtEConRel";
	public String emerge_phone			=		"txtEConMobile";
	public String emerg_save			=		"btnAddEContact";
 	public String emrge_Reset			=		"//*[@id=\"addPaneEmgContact\"]/div/input[2]";
 	public String depeent_txt			=		"Dependents";
 	public String dependnt_name			=		"txtDepName";
 	public String dependent_rel			=		"txtRelShip";
 	public String dependt_save			=		"btnAddDependent";
 	public String depandnt_xpath		=		"//*[@id=\"addPaneDependents\"]/div/input[2]";
 	public String link_imigrati			=		"Immigration";
 	public String passportno			=		"txtPPNo";
 	public String txtStatus				=		"txtI9status";
 	public String txt_star_rev			=		"atxtI9ReviewDat";
 	public String txt_issuedate			=		"txtPPIssDat";
 	public String txt_expirydate		=		"txtPPExpDat";
 	public String comment_txt			=		"txtComments";
 	public String add_imagi				=		"btnAddPassport";
 	public String reset_imigr			=		"//*[@id=\"addPaneImmigration\"]/div/input[2]";
 	public String photo_link			=		"Photograph";
 	public String save_photo			=		"//*[@id=\"photo\"]/div[1]/div[2]/div[2]/div/input";
 	public String job_link				=		"Job";
 	public String edit_job				=		"btnEditJob";
 	public String reset_job				=		"btnClearJob";
 	public String jb_title				=		"cmbJobTitle";
 	public String emp_stu_drop			=		"cmbType";
 	public String EEO_drop				=		"cmbEEOCat";
 	public String date_JOE				=		"txtJoinedDate";
 	public String txt_loc				=		"popLoc";
 	public String win_data				=		"DLF_IPL";
 	public String location_txt			=		"cmbNewLocationId";
 	public String assign_txt			=		"assignLocationButton";
 	public String loc_text				=		"Hello PL"; 	
 	public String salay_link			=		"Salary";
 	public String text_paygrade			=		"cmbSalaryGrade";
 	public String txt_bas_curre			=		"txtBasSal";
 	public String drop_month_sal		=		"cmbPayPeriod";
 	public String btn_slary				=		"btnAddPayment";
 	public String btn_salry_rest		=		"//*[@id=\"addPanePayments\"]/div/input[2]";
 	public String link_work				=		"Work experience";
 	public String txt_work_ex			=		"//*[@id=\"addPaneWorkExperience\"]/table/tbody/tr[1]/td[2]/input";
 	public String work_start			=		"atxtEmpExpFromDate";
 	public String txt_workstitle		=		"txtEmpExpJobTitle";
 	public String txt_workenddate		=		"atxtEmpExpToDate";
 	public String work_Save				=		"btnAddWrkExp";
 	public String reset_work			=		"//*[@id=\"addPaneWorkExperience\"]/div/input[2]";
 	
}

